"""empty message

Revision ID: 91cdf7082209
Revises: 
Create Date: 2018-12-31 19:56:47.655929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cdf7082209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dns_records_name_key', 'dns_records', type_='unique')
    op.create_unique_constraint(None, 'dns_records', ['uuid'])
    op.create_unique_constraint(None, 'dns_zones', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dns_zones', type_='unique')
    op.drop_constraint(None, 'dns_records', type_='unique')
    op.create_unique_constraint('dns_records_name_key', 'dns_records', ['name'])
    # ### end Alembic commands ###
